### ISSUE TITLE
Decrypting large files

### ISSUE THREAD

**Issue by dataO1** [LeSuisse/vault-gpg-plugin#171] opened 2022-06-07 09:01 UTC
Decrypting a fairly large GPG encrypted message (~700MB) crashes the plugin with the following debug log:
```
Jun 07 10:43:57 vault.gateway.semla.dfki.dev vault[11817]: 2022-06-07T10:43:57.371+0200 [DEBUG] secrets.vault-gpg-plugin.vault-gpg-plugin_3c840356.vault-gpg-plugin: starting plugin: path=/etc/vault.d/plugins/vault-gpg-plugin args=["/etc/vault.d/plugins/vault-gpg-plugin"]
Jun 07 10:43:57 vault.gateway.semla.dfki.dev vault[11817]: 2022-06-07T10:43:57.372+0200 [DEBUG] secrets.vault-gpg-plugin.vault-gpg-plugin_3c840356.vault-gpg-plugin: plugin started: path=/etc/vault.d/plugins/vault-gpg-plugin pid=11834
Jun 07 10:43:57 vault.gateway.semla.dfki.dev vault[11817]: 2022-06-07T10:43:57.372+0200 [DEBUG] secrets.vault-gpg-plugin.vault-gpg-plugin_3c840356.vault-gpg-plugin: waiting for RPC address: path=/etc/vault.d/plugins/vault-gpg-plugin
Jun 07 10:43:57 vault.gateway.semla.dfki.dev vault[11817]: 2022-06-07T10:43:57.410+0200 [DEBUG] secrets.vault-gpg-plugin.vault-gpg-plugin_3c840356.vault-gpg-plugin.vault-gpg-plugin: plugin address: network=unix address=/tmp/plugin262060118 timestamp="2022-06-07T10:43:57.410+0200"
Jun 07 10:43:57 vault.gateway.semla.dfki.dev vault[11817]: 2022-06-07T10:43:57.410+0200 [DEBUG] secrets.vault-gpg-plugin.vault-gpg-plugin_3c840356.vault-gpg-plugin: using plugin: version=4
Jun 07 10:43:57 vault.gateway.semla.dfki.dev vault[11817]: 2022-06-07T10:43:57.437+0200 [DEBUG] secrets.vault-gpg-plugin.vault-gpg-plugin_3c840356.vault-gpg-plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unimplemented desc = unknown service plugin.GRPCStdio"
```

**What i tried:**
I started with the vault CLI, which due to the `ARG_MAX` limit for parameter size did not work client side, so i created a small python script, that reads the file and sends it to the vault server via HTTPS request (using the `requests` package). For small files that worked, but at a certain threshold the plugin crashes.
Based on previous issues (#4 and #9), i increased the limits in the vault config:
```
max_request_size = -1
max_request_duration = "999s"
```

and i also gave the machine more than enough RAM to process the file (vault runs on a VM with 32G of RAM).

**Comment by LeSuisse** [comment] 2022-06-07 10:14
The error `rpc error: code = Unimplemented desc = unknown service plugin.GRPCStdio` is a bit strange.

Did you try with the "Show session key" endpoint? Since it does not need to output the whole file it is more likely to work.

https://github.com/LeSuisse/vault-gpg-plugin/blob/main/docs/http-api.md#show-session-key

**Comment by dataO1** [comment] 2022-06-07 15:24
So with the show-session-key endpoint it's still not working (client says peer closed session), but there is no error or warnings on the server side, which indicates that that's actually an error on the client side i would say.
I will try different http libs and will report back, if i can find anything out.

**Comment by LeSuisse** [comment] 2023-06-18 09:56
Closing as I cannot reproduce it with the show session key endpoint.

**Closed by LeSuisse** 2023-06-18 09:56 UTC
